### ISSUE TITLE
santiag

### ISSUE THREAD

**Issue by nobananasforyou** [HomeOfVapourSynthEvolution/havsfunc#25] opened 2020-01-13 02:39 UTC
Calling santiag with default parameters seems to result in a black line/border on the left hand side. Could you please investigate?  

Here's a screenshot comparison (source vs santiag): https://slow.pics/c/DNdrlT2R
Sample: https://www.dropbox.com/s/pgbhqnmfmntjxq1/sample.m2v?dl=0

Thank you.

**Comment by HolyWu** [comment] 2020-01-13 05:40
I can't reproduce it. Please post your full script.

**Comment by nobananasforyou** [comment] 2020-01-13 10:10
import vapoursynth as vs
import havsfunc as haf
import fvsfunc as fvf
core = vs.get_core()

src = core.d2v.Source(r'sample.d2v')
src = core.vivtc.VFM(src, order=1, cthresh=8)
src = core.vivtc.VDecimate(src)
src = fvf.Depth(src, 16)
src = haf.santiag(src, strh=1, strv=1, nns=4, type="nnedi3", nsize=0, qual=1, int16_prescreener=True, int16_predictor=True, exp=2)
src = fvf.Depth(src, 10)
src.set_output()

**Comment by HolyWu** [comment] 2020-01-14 03:31
I tried your script but I didn't get black stripe on the left side like yours.
[original](https://i.imgur.com/lSveddz.png)
[result](https://i.imgur.com/hhxqhQH.png)

Are your VS, nnedi3 and fmtconv plugins the latest version? Also are you using the original nnedi3 plugin or the newer znedi3 plugin? Try the other one and see if it still persists (remember to remove the dll from the autoload folder first).

**Comment by nobananasforyou** [comment] 2020-01-14 04:22
I beg to differ: https://slow.pics/c/fnY1VNX8

**Comment by HolyWu** [comment] 2020-01-14 04:58
The comparison is unfair. In your screenshots the black stripe is already significant even without 2x zooming in. I doubt that what you see is the result of interpolation from neighboring pixels. Try the AviSynth version and see if you get similar result.

**Comment by nobananasforyou** [comment] 2020-01-14 12:46
I get the same result in avs+.

**Comment by HolyWu** [comment] 2020-01-14 14:42
Then santiag has nothing to do with it. The black stripe on the very left side in the source affects the interpolation of nnedi3. Maybe try some filter/function like edgefixer or bbmod before invoking santiag and see how it works. Closing this as it's not a bug in santiag.

**Closed by HolyWu** 2020-01-14 14:42 UTC

**Comment by nobananasforyou** [comment] 2020-01-14 18:04
okay
